    merchant_1 = Merchant.create!(name: 'Hair Care')
    merchant_2 = Merchant.create!(name: 'Hayleys Comcics')

    BulkDiscount.create!(markdown: 10, quantity_threshold: 10, merchant_id: merchant_1.id)
    BulkDiscount.create!(markdown: 20, quantity_threshold: 20, merchant_id: merchant_1.id)
    BulkDiscount.create!(markdown: 30, quantity_threshold: 30, merchant_id: merchant_2.id)

    customer_1 = Customer.create!(first_name: 'Joey', last_name: 'Smith')
    customer_2 = Customer.create!(first_name: 'Cecilia', last_name: 'Jones')
    customer_3 = Customer.create!(first_name: 'Mariah', last_name: 'Carrey')
    customer_4 = Customer.create!(first_name: 'Leigh Ann', last_name: 'Bron')
    customer_5 = Customer.create!(first_name: 'Sylvester', last_name: 'Nader')
    customer_6 = Customer.create!(first_name: 'Herber', last_name: 'Kuhn')

    invoice_1 = Invoice.create!(customer_id: customer_1.id, status: 2)
    invoice_2 = Invoice.create!(customer_id: customer_1.id, status: 2)
    invoice_3 = Invoice.create!(customer_id: customer_2.id, status: 2)
    invoice_4 = Invoice.create!(customer_id: customer_3.id, status: 2)
    invoice_5 = Invoice.create!(customer_id: customer_4.id, status: 2)
    invoice_6 = Invoice.create!(customer_id: customer_5.id, status: 2)
    invoice_7 = Invoice.create!(customer_id: customer_6.id, status: 1)

    item_1 = Item.create!(name: "Shampoo", description: "This wahes your hair", unit_price: 10, merchant_id: merchant1.id)
    item_2 = Item.create!(name: "Conditioner", description: "This makes your hair shiny", unit_price: 8, merchant_id: merchant1.id)
    item_3 = Item.create!(name: "Brush", description: "This takes out tangles", unit_price: 5, merchant_id: merchant1.id)
    item_4 = Item.create!(name: "Hair tie", description: "This holds up your hair", unit_price: 1, merchant_id: merchant1.id)

    InvoiceItem.create!(invoice_id: invoice_1.id, item_id: item_1.id, quantity: 1, unit_price: 10, status: 0)
    InvoiceItem.create!(invoice_id: invoice_1.id, item_id: item_2.id, quantity: 1, unit_price: 8, status: 0)
    InvoiceItem.create!(invoice_id: invoice_2.id, item_id: item_3.id, quantity: 1, unit_price: 5, status: 2)
    InvoiceItem.create!(invoice_id: invoice_3.id, item_id: item_4.id, quantity: 1, unit_price: 5, status: 1)
    InvoiceItem.create!(invoice_id: invoice_4.id, item_id: item_4.id, quantity: 1, unit_price: 5, status: 1)
    InvoiceItem.create!(invoice_id: invoice_5.id, item_id: item_4.id, quantity: 1, unit_price: 5, status: 1)
    InvoiceItem.create!(invoice_id: invoice_6.id, item_id: item_4.id, quantity: 1, unit_price: 5, status: 1)

    Transaction.create!(credit_card_number: 203942, result: 1, invoice_id: invoice_1.id)
    Transaction.create!(credit_card_number: 230948, result: 1, invoice_id: invoice_3.id)
    Transaction.create!(credit_card_number: 234092, result: 1, invoice_id: invoice_4.id)
    Transaction.create!(credit_card_number: 230429, result: 1, invoice_id: invoice_5.id)
    Transaction.create!(credit_card_number: 102938, result: 1, invoice_id: invoice_6.id)
    Transaction.create!(credit_card_number: 879799, result: 1, invoice_id: invoice_7.id)
    Transaction.create!(credit_card_number: 203942, result: 1, invoice_id: invoice_2.id)

